name: テスト実行

on:
  pull_request:
    types:
      - labeled
      - synchronize
  workflow_dispatch:

jobs:
  test:
    if: |
      contains(toJSON(github.event.pull_request.labels), 'レビュー待ち') || contains(toJSON(github.event.pull_request.labels), 'Waiting Review')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.15.0]

    steps:
      - name: ソースコードのチェックアウト
        uses: actions/checkout@v4

      - name: pnpmのインストール
        uses: pnpm/action-setup@v4
        with:
          version: 9.7.0

      - name: Node.jsバージョンの設定 ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: pnpmキャッシュの復元
        uses: actions/cache@v4
        with:
          path: /home/runner/setup-pnpm/node_modules/.bin/store/v3
          key: pnpm-cache-${{ matrix.node-version }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-cache-${{ matrix.node-version }}-

      - name: 依存関係のインストール
        run: pnpm install --frozen-lockfile

      - name: Vitestとカバレッジの実行
        run: pnpm test:coverage
        env:
          CI: true

      - name: カバレッジレポートのアップロード
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: logs/coverage
